---
- name: Deploy network components
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
    - name: Create VPC network
      amazon.aws.ec2_vpc_net:
        name: "{{ project_tag }}-vpc"
        cidr_block: 10.10.0.0/16
        tags:
          project: "{{ project_tag }}"
        state: present
      register: vpc_net

    - name: Create VPC subnets
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_net.vpc.id }}"
        cidr: 10.10.{{ item }}.0/24
        tags:
          project: "{{ project_tag }}"
        state: present
      loop: "{{ range(0, num_of_subnets) | list }}"
      loop_control:
        label: VPC Subnet {{ item }}

    - name: Create a VPC Internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_net.vpc.id }}"
        tags:
          project: "{{ project_tag }}"
        state: present
      register: vpc_igw

    - name: Gather route table details
      amazon.aws.ec2_vpc_route_table_info:
        filters:
          vpc-id: "{{ vpc_net.vpc.id }}"
      register: vpc_route_tables

    - name: Create VPC route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_net.vpc.id }}"
        route_table_id: "{{ vpc_route_tables.route_tables.0.id }}"
        lookup: id
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ vpc_igw.gateway_id }}"
        purge_routes: no
        tags:
          project: "{{ project_tag }}"
        state: present
      register: vpc_route_table
