---
- name: Deploy EC2 prerequisites
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
    - name: Get VPC details
      amazon.aws.ec2_vpc_net_info:
        filters:
          "tag:project": "{{ project_tag }}"
      register: vpc_results

    - name: Create security group
      amazon.aws.ec2_security_group:
        name: "{{ project_tag }}-sg"
        description: Red Hat Discovery demo security group
        vpc_id: "{{ vpc_results.vpcs.0.id }}"
        rules:
          - proto: tcp
            ports: "{{ open_ports }}"
            cidr_ip: 0.0.0.0/0
            rule_desc: all
        tags:
          project: "{{ project_tag }}"
        state: present
      register: security_group

    - name: Create EC2 key pair
      amazon.aws.ec2_key:
        name: "{{ project_tag }}-keypair"
        key_material: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        tags:
          project: "{{ project_tag }}"
        state: present
      register: ec2_keypair
